version: "3.7"

services:

    # source : https://docs.min.io/docs/deploy-minio-on-docker-compose.html
    minio:
        image: minio/minio:RELEASE.2021-04-06T23-11-00Z-24-g409125240
        command: server /data
        ports:
            - 9000:9000
        volumes:
            - /srv/docker/prefect/minio:/data
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123

    weather:
        build: .
        command: python3 /usr/app/weather.py
        volumes:
            - type: bind
              source: ./weather.py
              target: /usr/app/weather.py
              read_only: true
            - type: bind
              source: ./s3_utils.py
              target: /usr/app/s3_utils.py
              read_only: true
            - type: bind
              source: ./config.toml
              target: /root/.prefect/config.toml
              read_only: true
        depends_on:
            - minio
