version: "3.8"

services:

    registry:
        restart: always
        image: registry:2.8.1
        ports:
            - 5000:5000
        volumes:
            - ./registry/auth:/auth
            - registry_data:/data
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data

    # The script should have access to Docker in order to register
    # the Dockerized script (`execution.Dockerfile`) in Prefect.
    weather:
        build: .
        entrypoint: ["/bin/sh", "-c"]
        command: 
          - |
            docker login -u=myusername -p=test http://172.17.0.1:5000
            python3 /usr/app/weather.py
        privileged: true # forced for Docker DinD
        volumes:
            - /srv/docker/prefect/flows:/root/.prefect/flows
            - type: bind
              source: ./weather.py
              target: /usr/app/weather.py
              read_only: true
            - type: bind
              source: ./config.toml
              target: /root/.prefect/config.toml
              read_only: true
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              read_only: true
        depends_on:
            - registry

volumes:
    registry_data:
